[package]
name = "vm"
version = "0.1.0"
authors = ["Samuel Barney <samjbarney@gmail.com>"]
edition = "2018"

[features]
default = ["u16"]

u16 = []
u32 = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
